name: Publish image to Docker Hub          #This sets the name of the workflow.
on:
  [workflow_dispatch]    #This specifies that the workflow can be manually triggered via the GitHub Actions interface

jobs:                      #This section defines the jobs that will be run as part of the workflow
  publish_images:               #This is the name of the job. It contains the steps to be executed.
    runs-on: ubuntu-latest               #Specifies the environment in which the job will run
    steps:
      - name: checkout      #checks out the repository's code so that it can be used in subsequent steps
        uses: actions/checkout@v4             #specifies the GitHub Action to use for checking out the code
      - name: build image
        run: |                #indicates that multiple lines of shell commands will be executed
          docker build . -t leovyjunu/getting-started-app:v2          #builds Docker images
      - name: push image to docker hub
        run: |
          docker login -u leovyjunu -p ${{ secrets.DOCKER_HUB_TOKEN }}              #logs into Docker Hub
          docker push leovyjunu/getting-started-app:v2                #pushes the Docker image to Docker Hub
